name: Test and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  ansible-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Ansible and ansible-lint
        run: |
          pip install ansible ansible-lint

      - name: Run ansible-lint
        run: ansible-lint

      - name: Test dry-run before deployment
        run: ansible-playbook -i tests/inventory tests/test.yml --check --diff | tee /dev/stderr | awk '/changed=[0]/ { exit 1 }'

      - name: Test first deployment
        run: ansible-playbook -i tests/inventory tests/test.yml

      - name: Test dry-run after deployment
        run: ansible-playbook -i tests/inventory tests/test.yml --check --diff | tee /dev/stderr | awk '/changed=[1-9]/ { exit 1 }'

      - name: Test re-deployment
        run: ansible-playbook -i tests/inventory tests/test.yml

      - name: Test dry-run after re-deployment
        run: ansible-playbook -i tests/inventory tests/test.yml --check --diff | tee /dev/stderr | awk '/changed=[1-9]/ { exit 1 }'

      - name: Test cleanup
        run: ansible-playbook -i tests/inventory tests/cleanup.yml
